package com.gestaofacil.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Empresa que usa o sistema (RF02).
 *
 * E a raiz do isolamento multiempresa: todas as outras oito tabelas do modelo
 * apontam para uma empresa, e toda consulta do sistema filtra por ela. Por isso
 * a Empresa e a unica tabela que NAO tem a coluna empresa_id.
 */
@Entity
@Table(name = "empresa")
public class Empresa {

    /**
     * Chave primaria. IDENTITY significa que quem gera o numero e o proprio
     * banco; no PostgreSQL isso vira uma coluna
     * "bigint generated by default as identity". O Java so le o valor
     * depois de salvar.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Nome da empresa como aparece nas telas. Ex.: "Construtora Teste". */
    @Column(nullable = false, length = 120)
    private String nome;

    /**
     * Identificador curto usado no endereco de acesso (RF01/RF02).
     * Ex.: "construtora-teste" -> o sistema e acessado em /construtora-teste.
     *
     * unique = true faz o banco criar um indice unico: ele recusa duas
     * empresas com o mesmo identificador, mesmo que uma tela deixe passar.
     */
    @Column(nullable = false, unique = true, length = 60)
    private String identificador;

    /**
     * Como esta empresa chama o centro de custo, no singular. Para a
     * construtora e "Obra"; para uma transportadora poderia ser "Rota".
     *
     * Regra do projeto: nenhum template ou mensagem escreve "Obra" fixo -
     * o texto sai sempre daqui.
     */
    @Column(name = "rotulo_cc_singular", nullable = false, length = 40)
    private String rotuloCcSingular;

    /** O mesmo rotulo no plural. Ex.: "Obras". Usado em titulos e menus. */
    @Column(name = "rotulo_cc_plural", nullable = false, length = 40)
    private String rotuloCcPlural;

    /**
     * O JPA exige um construtor sem argumentos para conseguir criar o objeto
     * ao ler uma linha do banco. E por isso que ele existe.
     */
    public Empresa() {
    }

    /** Construtor de conveniencia, usado pela carga inicial. */
    public Empresa(String nome, String identificador,
                   String rotuloCcSingular, String rotuloCcPlural) {
        this.nome = nome;
        this.identificador = identificador;
        this.rotuloCcSingular = rotuloCcSingular;
        this.rotuloCcPlural = rotuloCcPlural;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getIdentificador() {
        return identificador;
    }

    public void setIdentificador(String identificador) {
        this.identificador = identificador;
    }

    public String getRotuloCcSingular() {
        return rotuloCcSingular;
    }

    public void setRotuloCcSingular(String rotuloCcSingular) {
        this.rotuloCcSingular = rotuloCcSingular;
    }

    public String getRotuloCcPlural() {
        return rotuloCcPlural;
    }

    public void setRotuloCcPlural(String rotuloCcPlural) {
        this.rotuloCcPlural = rotuloCcPlural;
    }
}
