package com.gestaofacil.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import org.hibernate.annotations.ColumnDefault;

import java.time.LocalDateTime;

/**
 * Empresa que usa o sistema (RF02).
 *
 * E a raiz do isolamento multiempresa: todas as outras oito tabelas do modelo
 * apontam para uma empresa, e toda consulta do sistema filtra por ela. Por isso
 * a Empresa e a unica tabela que NAO tem a coluna empresa_id.
 */
@Entity
@Table(name = "empresa")
public class Empresa {

    /**
     * Identificador da empresa reservada da equipe do sistema (#002-RN010).
     *
     * Ela nao e uma construtora cliente: existe so porque todo usuario precisa
     * de uma empresa, e o Operador tambem e um usuario. Os Operadores entram
     * por /gestao-facil/login.
     *
     * E uma constante, e nao uma coluna, porque existe UMA empresa assim no
     * sistema inteiro e ela nunca muda. A listagem, a edicao e a recuperacao
     * de acesso usam esta constante para deixa-la de fora.
     */
    public static final String IDENTIFICADOR_DA_EQUIPE = "gestao-facil";

    /**
     * Chave primaria. IDENTITY significa que quem gera o numero e o proprio
     * banco; no PostgreSQL isso vira uma coluna
     * "bigint generated by default as identity". O Java so le o valor
     * depois de salvar.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Nome da empresa como aparece nas telas. Ex.: "Construtora Teste". */
    @Column(nullable = false, length = 120)
    private String nome;

    /**
     * Identificador curto usado no endereco de acesso (RF01/RF02).
     * Ex.: "construtora-teste" -> o sistema e acessado em /construtora-teste.
     *
     * unique = true faz o banco criar um indice unico: ele recusa duas
     * empresas com o mesmo identificador, mesmo que uma tela deixe passar.
     */
    @Column(nullable = false, unique = true, length = 60)
    private String identificador;

    /**
     * Como esta empresa chama o centro de custo, no singular. Para a
     * construtora e "Obra"; para uma transportadora poderia ser "Rota".
     *
     * Regra do projeto: nenhum template ou mensagem escreve "Obra" fixo -
     * o texto sai sempre daqui.
     */
    @Column(name = "rotulo_cc_singular", nullable = false, length = 40)
    private String rotuloCcSingular;

    /** O mesmo rotulo no plural. Ex.: "Obras". Usado em titulos e menus. */
    @Column(name = "rotulo_cc_plural", nullable = false, length = 40)
    private String rotuloCcPlural;

    /**
     * #002-RF06 e RN013: empresa inativa nao aceita login de nenhum usuario.
     * Regra 3 do projeto: empresa tambem nao e apagada, so desligada.
     *
     * ARMADILHA - POR QUE O @ColumnDefault
     * Sem ele, o ddl-auto=update mandaria ao PostgreSQL de voces
     * "alter table empresa add column ativa boolean not null", e o banco
     * recusa: a construtora-teste, que ja existe, ficaria com a coluna vazia.
     * O Hibernate so escreve o erro no console e segue em frente, e o sistema
     * quebra depois, longe da causa. Com o default o comando vira
     * "... boolean default true not null" e as linhas antigas nascem ativas.
     * Vale para TODA coluna NOT NULL acrescentada a tabela que ja tem dados.
     */
    @ColumnDefault("true")
    @Column(nullable = false)
    private boolean ativa = true;

    /**
     * Quando a empresa foi cadastrada pela tela (#002). Nulo nas empresas da
     * carga inicial, que nao passaram por ela.
     */
    @Column(name = "data_cadastro")
    private LocalDateTime dataCadastro;

    /**
     * Qual Operador cadastrou a empresa - o "historico" pedido pelo card #002.
     * E por isso que as contas de Operador sao nominais (#002-RN011): uma
     * conta compartilhada nao diria quem foi.
     *
     * Aponta para um Usuario da empresa reservada. Nulo nas empresas da carga
     * inicial. LAZY: so a listagem de empresas precisa dele, e ela o pede
     * explicitamente (veja o @EntityGraph no EmpresaRepository).
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cadastrada_por_id")
    private Usuario cadastradaPor;

    /**
     * O JPA exige um construtor sem argumentos para conseguir criar o objeto
     * ao ler uma linha do banco. E por isso que ele existe.
     */
    public Empresa() {
    }

    /** Construtor de conveniencia, usado pela carga inicial. */
    public Empresa(String nome, String identificador,
                   String rotuloCcSingular, String rotuloCcPlural) {
        this.nome = nome;
        this.identificador = identificador;
        this.rotuloCcSingular = rotuloCcSingular;
        this.rotuloCcPlural = rotuloCcPlural;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getIdentificador() {
        return identificador;
    }

    public void setIdentificador(String identificador) {
        this.identificador = identificador;
    }

    public String getRotuloCcSingular() {
        return rotuloCcSingular;
    }

    public void setRotuloCcSingular(String rotuloCcSingular) {
        this.rotuloCcSingular = rotuloCcSingular;
    }

    public String getRotuloCcPlural() {
        return rotuloCcPlural;
    }

    public void setRotuloCcPlural(String rotuloCcPlural) {
        this.rotuloCcPlural = rotuloCcPlural;
    }

    public boolean isAtiva() {
        return ativa;
    }

    public void setAtiva(boolean ativa) {
        this.ativa = ativa;
    }

    /** true para a empresa reservada da equipe (#002-RN010). */
    public boolean isDaEquipe() {
        return IDENTIFICADOR_DA_EQUIPE.equals(identificador);
    }

    public LocalDateTime getDataCadastro() {
        return dataCadastro;
    }

    public void setDataCadastro(LocalDateTime dataCadastro) {
        this.dataCadastro = dataCadastro;
    }

    public Usuario getCadastradaPor() {
        return cadastradaPor;
    }

    public void setCadastradaPor(Usuario cadastradaPor) {
        this.cadastradaPor = cadastradaPor;
    }
}
